### ISSUE TITLE
Some videos fail to initialize

### ISSUE THREAD

**Issue by ys-sherzad** [GeekyAnts/flick-video-player#34] opened 2020-09-17 18:50 UTC
Not sure if this flick's problem or `video_player` itself. I have built a similar example like `FlickMultiPlayer` (Feed). the video in the example (butterfly) plays fine in the Feed, but I have tried playing some other videos and some don't run at all. any help is appreciated

LOG
```
I/ACodec  (31729):  [] Now uninitialized
I/ACodec  (31729): [] onAllocateComponent
I/OMXClient(31729): IOmx service obtained
I/ACodec  (31729): [OMX.qcom.video.decoder.avc] Now Loaded
I/ACodec  (31729):  [OMX.qcom.video.decoder.avc] Now uninitialized
I/ACodec  (31729):  [] Now kWhatShutdownCompleted event : 8519
I/MediaCodec(31729): Codec shutdown complete
W/MediaCodecRenderer(31729): Failed to initialize decoder: OMX.qcom.video.decoder.avc
W/MediaCodecRenderer(31729): android.media.MediaCodec$CodecException: Error 0xffffec77
W/MediaCodecRenderer(31729): 	at android.media.MediaCodec.native_configure(Native Method)
W/MediaCodecRenderer(31729): 	at android.media.MediaCodec.configure(MediaCodec.java:1960)
W/MediaCodecRenderer(31729): 	at android.media.MediaCodec.configure(MediaCodec.java:1889)
W/MediaCodecRenderer(31729): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
W/MediaCodecRenderer(31729): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:805)
W/MediaCodecRenderer(31729): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
W/MediaCodecRenderer(31729): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
W/MediaCodecRenderer(31729): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
W/MediaCodecRenderer(31729): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
W/MediaCodecRenderer(31729): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
W/MediaCodecRenderer(31729): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
W/MediaCodecRenderer(31729): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
W/MediaCodecRenderer(31729): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
W/MediaCodecRenderer(31729): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/MediaCodecRenderer(31729): 	at android.os.Looper.loop(Looper.java:214)
W/MediaCodecRenderer(31729): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(31729): Playback error.
E/ExoPlayerImplInternal(31729): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [3840, 2160, -1.0], [-1, -1])
E/ExoPlayerImplInternal(31729): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
E/ExoPlayerImplInternal(31729): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
E/ExoPlayerImplInternal(31729): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
E/ExoPlayerImplInternal(31729): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
E/ExoPlayerImplInternal(31729): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
E/ExoPlayerImplInternal(31729): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
E/ExoPlayerImplInternal(31729): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
E/ExoPlayerImplInternal(31729): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(31729): 	at android.os.Looper.loop(Looper.java:214)
E/ExoPlayerImplInternal(31729): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(31729): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [3840, 2160, -1.0], [-1, -1])
E/ExoPlayerImplInternal(31729): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
E/ExoPlayerImplInternal(31729): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
E/ExoPlayerImplInternal(31729): 	... 9 more
E/ExoPlayerImplInternal(31729): Caused by: android.media.MediaCodec$CodecException: Error 0xffffec77
E/ExoPlayerImplInternal(31729): 	at android.media.MediaCodec.native_configure(Native Method)
E/ExoPlayerImplInternal(31729): 	at android.media.MediaCodec.configure(MediaCodec.java:1960)
E/ExoPlayerImplInternal(31729): 	at android.media.MediaCodec.configure(MediaCodec.java:1889)
E/ExoPlayerImplInternal(31729): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
E/ExoPlayerImplInternal(31729): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:805)
E/ExoPlayerImplInternal(31729): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
E/ExoPlayerImplInternal(31729): 	... 10 more
```

**Comment by ahujaraghav** [comment] 2020-09-21 05:49
@ys-sherzad which video format are not working for you?

**Comment by ys-sherzad** [comment] 2020-09-23 10:04
@ahujaraghav all videos are .mp4 (downloaded from pexels.com)

**Comment by ahujaraghav** [comment] 2020-09-26 05:16
@ys-sherzad where have you hosted the videos?

**Comment by ys-sherzad** [comment] 2020-09-26 05:19
@ahujaraghav I added them to the `/assets` folder

**Comment by deut818** [comment] 2021-03-26 16:08
Having the same issue here what should i do

**Comment by yasir-netlinks** [comment] 2021-03-29 05:16
@deut818 Hi there, have you found a solution for the problem!

**Comment by ahujaraghav** [comment] 2021-04-01 13:40
@yasir-netlinks @deut818 can you please share the video you are trying to play.

**Comment by kamlesh1687** [comment] 2021-04-13 07:12
I have the same issue with flick multi player,some videos are failed to initialize

**Comment by geekruchika** [comment] 2021-04-19 09:36
> I have the same issue with flick multi player,some videos are failed to initialize

What exceptions are you getting?

**Comment by geekruchika** [comment] 2021-07-30 13:40
Closing this PR due to lack of information. Please try out the latest version and feel free to open this issue if still reproducible.

**Closed by geekruchika** 2021-07-30 13:40 UTC

**Comment by adrianvintu** [comment] 2022-10-30 19:14
It happens to me as well - Galaxy Tab A8 Android 11.

Steps to reproduce:
1. download the code from https://github.com/GeekyAnts/flick-video-player/
2. run on tablet - all videos play
3. change DefaultPlayer url to my video
```
  void initState() {
    super.initState();
    flickManager = FlickManager(
      videoPlayerController: VideoPlayerController.network(
        "https://stop-anxietate.ro/app_content/video/front/Ce%20cauzeaz%C4%83%20anxietatea%20%E2%80%93%20partea%202.mp4",
        closedCaptionFile: _loadCaptions(),
      ),
    );
  }
```
4. error, cannot play - see attached log

[log.zip](https://github.com/GeekyAnts/flick-video-player/files/9896640/log.zip)


Related issue: https://github.com/google/ExoPlayer/issues/6168

Someone said they found a fix, but I cannot implement it.

https://github.com/google/ExoPlayer/issues/6168#issuecomment-1009619889
